version: '3.4'

services:
  frete-db:
    image: postgres:12-alpine    
    environment:
      TZ: America/Sao_Paulo 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bruno28postgres
      POSTGRES_DB: db_frete_azship
    ports:
      - 5434:5432
    networks:
      - frete-network
  adm-azs-shipping:
    image: adm-azs-shipping
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://frete-db:5432/db_frete_azship
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: bruno28postgres
    ports:
      - 8081:8080
    depends_on:
      - frete-db
    networks:
      - frete-network      
networks:
  frete-network:
    driver: bridge